# Generated by Django 5.1 on 2024-09-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolucionfinal',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='resoluciones/'),
        ),
    ]
